export const ROUTES = {
    root: '/',
    teams: '/teams',
    programs: '/programs',
    casestudiesLancet: '/cases/lancet',
    casestudiesYandex: '/cases/yandex',
    casestudiesGoBeyond: '/cases/gobeyond',
    casestudiesUAE: '/cases/uae',
    base: '/baza',
    vibecoding: '/vibecoding',
    edu: '/edu',
    agents: '/agents',
    jobsPm: '/jobs/pm',
    jobsApply: '/jobs/:position/apply',
    newyear2026: '/newyear2026',
    notFound: '*',
};